---
title: Seguro de Automóvel
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Seguro de Automóvel
webName: Segurodeautomovel.org
description: Cote aqui o seguro do seu carro!
email: your-email@example.com
baseurl: ''
url: https://www.segurodeautomovel.org
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-paginate-v2
- jekyll-minimagick
pagination:
  enabled: true
  per_page: 12
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
ampdir: amp
facebook:
  app_id: 1675535542684820
twitter:
  username: 
  card: summary
exclude:
- Gemfile.lock
- node_modules
include:
- Gemfile
encoding: utf-8
blacklistedTags:
- cornerstone
- Featured
- cornestone
- c
mini_magick:
    thumbnail: # Preset name
        source: uploads # source directory - change this to whatever you want
        destination: uploads/thumbnail # generated destination directory
        resize: "80x80^" # standard imagemagick options - you can chain multiple commands
        gravity: "center"
        extent: "80x80"
    large: # Preset name
        source: uploads # source directory - change this to whatever you want
        destination: uploads/large # generated destination directory
        resize: "150x150^" # standard imagemagick options - you can chain multiple commands
        gravity: "center"
        extent: "150x150"   